openapi: 3.0.0
info:
  title: API EgaPro
  description: API pour la distribution des données EgaPro par SIREN
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
    description: Serveur local

paths:
  /api/egapro/{siren}:
    get:
      summary: Récupère les données EgaPro par SIREN
      description: Retourne les informations d'une entreprise basée sur le SIREN
      parameters:
        - name: siren
          in: path
          required: true
          description: Numéro SIREN de l'entreprise
          schema:
            type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  siren:
                    type: string
                  entreprise:
                    type: string
                  region:
                    type: string
                  departement:
                    type: string
                  index:
                    type: number
        '404':
          description: SIREN non trouvé