# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: egapro.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'egapro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65gapro.proto\x12\x06\x65gapro\"\x1e\n\rEgaProRequest\x12\r\n\x05siren\x18\x01 \x01(\t\"X\n\x0e\x45gaProResponse\x12\x12\n\nentreprise\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65partement\x18\x03 \x01(\t\x12\r\n\x05index\x18\x04 \x01(\x02\x32O\n\rEgaProService\x12>\n\rGetEgaProData\x12\x15.egapro.EgaProRequest\x1a\x16.egapro.EgaProResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'egapro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EGAPROREQUEST']._serialized_start=24
  _globals['_EGAPROREQUEST']._serialized_end=54
  _globals['_EGAPRORESPONSE']._serialized_start=56
  _globals['_EGAPRORESPONSE']._serialized_end=144
  _globals['_EGAPROSERVICE']._serialized_start=146
  _globals['_EGAPROSERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
